services:
  python:
    image: tugboatqa/ubuntu:xenial
    expose: 8000
    default: true
    http: true
    https: true
    https_redirect: true
    commands:
      init:
        - ./.tugboat/install.sh
      build:
        - su frappe -c "cd /home/frappe/frappe-bench && nohup bench start &"