services:
  python:
    image: tugboatqa/ubuntu:xenial
    expose: 8000
    default: true
    http: true
    https: true
    https_redirect: true
    depends: redis
    commands:
      init:
        - ./.tugboat/install.sh
      build:
        - ./.tugboat/build.sh
  redis:
    image: tugboatqa/redis:4.0.9